version: '2'

services:
  monero-cli:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        PROTOCOL: https://
        BINARIES_URL: <some_gitlab_or_github_location>
        DEPLOY_TOKEN: DEPLOY-TOKEN
        DEPLOY_USER: DEPLOY-USER
    command: monero-wallet-cli --testnet --wallet-file wallet --password-file wallet.passwd
    volumes:
      - <path/to/and/including/wallet_folder>:/monero
    stdin_open: true
    tty: true
    environment:
      - USER_ID=1000
      - LOG_LEVEL=0
      - DAEMON_HOST=<host>
      - DAEMON_PORT=28081
    logging:
      driver: "json-file"
      options:
        max-size: 10m
        max-file: "3"
    restart: unless-stopped
