version: '2'

services:
  monero-cli:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        BINARIES_URL: <some_gitlab_or_github_location>
        ACCESS_TOKEN: PRIVATE-TOKEN
    command: monero-wallet-cli --testnet --wallet-file wallet --password-file wallet.passwd
    volumes:
      - <path_to_contents_of_wallet_folder>:/monero
    stdin_open: true
    tty: true
    environment:
      - USER_ID=1000
      - LOG_LEVEL=0
      - DAEMON_HOST=<host>
      - DAEMON_PORT=28081
    logging:
      driver: "json-file"
      options:
        max-size: 10m
        max-file: "3"
    restart: unless-stopped
