version: '2'

services:
  monero-rpc:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        BINARIES_URL: <some_gitlab_or_github_location>
        ACCESS_TOKEN: PRIVATE-TOKEN
    command: monero-wallet-rpc --testnet --wallet-file wallet --password-file wallet.passwd --disable-rpc-login
    volumes:
      - <path_to_contents_of_wallet_folder>:/monero
    ports:
      - "28083:28083"
    environment:
      - USER_ID=1000
      - LOG_LEVEL=0
      - DAEMON_HOST=<host>
      - DAEMON_PORT=28081
      - RPC_BIND_IP=0.0.0.0
      - RPC_BIND_PORT=28083
    logging:
      driver: "json-file"
      options:
        max-size: 10m
        max-file: "3"
    restart: unless-stopped
