#!/bin/bash

docker build --build-arg ACCESS_TOKEN=$ACCESS_TOKEN --build-arg BINARIES_URL=$BINARIES_URL -t $IMAGE_NAME .

# some kind of test
docker run --rm --entrypoint='' $IMAGE_NAME  monerod --version
ERROR_MONEROD="$?"
docker run --rm --entrypoint='' $IMAGE_NAME  monero-wallet-rpc --version
ERROR_MONERO_RPC="$?"
docker run --rm --entrypoint='' $IMAGE_NAME  monero-wallet-cli --version
ERROR_MONERO_CLI="$?"

# none of them should exit with 1
if [ "$ERROR_MONEROD" -eq 1 -o "$ERROR_MONERO_RPC" -eq 1 -o "$ERROR_MONERO_CLI" -eq 1 ]; then
    echo "error code monerod: $ERROR_MONEROD"
    echo "error code monero-wallet-rpc: $ERROR_MONERO_RPC"
    echo "error code monero-wallet-cli: $ERROR_MONERO_CLI"
    exit 1
fi
