#!/bin/bash

if [ "$RELEASE_BRANCH" = "$SOURCE_BRANCH" ]; then
  curl -X POST \
       -F token=$MONERO_TESTNET_TOKEN \
       -F ref=$SOURCE_BRANCH \
       $MONERO_TESTNET_URL
fi

if [ "$PATCHED_BRANCH" = "$SOURCE_BRANCH" ]; then
  curl -X POST \
       -F token=$MONERO_DAEMON_TOKEN \
       -F ref=$BRANCH_MAIN \
       $MONERO_DAEMON_URL
  curl -X POST \
       -F token=$MONERO_DAEMON_TOKEN \
       -F ref=$BRANCH_STAGE \
       $MONERO_DAEMON_URL
fi
